FROM python:3.9-slim-buster

WORKDIR /usr/src/app

RUN python -m pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7007
COPY train.py .
COPY training_iterations.txt .
CMD [ "python", "train.py" ]
# ARG model_file
# COPY $model_file .
#
# COPY app.py .